micronaut:
  application:
    name: hw18-micronault
    security:
#Enable Micronaut’s security capabilities
      enabled: true
      endpoints:
#Expose /login endpoint
        login:
          enabled: true
#Expose /oauth/access_token endpoint as defined by section 6 of the OAuth 2.0 spec - Refreshing an Access Token.
        oauth:
          enabled: true
      token:
#Enable JWT based authentication
        jwt:
          enabled: true
          signatures:
            secret:
#You can create a SecretSignatureConfiguration named generator via configuration as illustrated above. The generator signature is used to sign the issued JWT claims.
              generator:
#Change this by your own secret and keep it safe (do not store this in your VCS)
                secret: pleaseChangeThisSecretForANewOne
